'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  class mvorder extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
      mvorder.hasMany(models.mvOrderItem, {
        foreignKey: "Orderid"

      })
      mvorder.hasOne(models.mvOrderSpecialCharge, {
        foreignKey: "orderId"

      })
      mvorder.hasOne(models.mvOrderWeightReconcilation, {
        foreignKey: "orderId",
        as: 'weightReconcilation'

      })
      mvorder.belongsTo(models.mvUser, {
        foreignKey: 'userId',
        as: "user"
      })
      mvorder.belongsTo(models.mvUser, {
        foreignKey: 'vendorId',
        as: "vendor"
      })
      mvorder.belongsTo(models.mvUser, {
        foreignKey: 'kamId',
        as: "kam"
      })
      mvorder.belongsTo(models.mvUser, {
        foreignKey: 'vendorOldId',
        as: "vendorold"
      })
      mvorder.belongsTo(models.mvOrderStatusType, {
        foreignKey: "latestStatus",
        as: 'orderStatus'
      })
      mvorder.belongsTo(models.mvOrderStatusType, {
        foreignKey: "latestStatus",
        as: 'latestorderstatus'
      })
    }
  }
  mvorder.init({
    Order_id: {
      type: DataTypes.STRING
    },
    vendorId: {
      type: DataTypes.UUID, // Use UUID data type,     
    },
    PaymentId: {
      type: DataTypes.INTEGER
    },
    gatewayOrderId: {
      type: DataTypes.STRING //order id generated by gateway
    },
    transactionId: {
      type: DataTypes.STRING //generated by payment gateway
    },
    transactionData: {
      type: DataTypes.STRING
    },
    paymentStatus: {
      type: DataTypes.STRING //"Initiated,Completed,Failed,Cancelled"

    },
    paymentMethod: {
      type: DataTypes.STRING // from payment gateway"card,net banking,credit card,debit card"

    },
    paymentMode: {
      type: DataTypes.STRING //"Gateway,Wallet,Credit"      
    },
    vendorOldId: {
      type: DataTypes.UUID
    },
    VtotalAdditionalAmount: {
      type: DataTypes.DECIMAL(10, 2)
    },
    masterDocketURL: {
      type: DataTypes.STRING
    },
    docketURL: {
      type: DataTypes.STRING
    },
    isVendorChanged: {
      type: DataTypes.BOOLEAN,
      defaultValue: false
    },
    invoiceNumber: {
      type: DataTypes.STRING
    },
    isPayLater: {
      type: DataTypes.BOOLEAN,
      defaultValue: false
    },
    Serviceid: {
      type: DataTypes.TINYINT
    },
    Frompincode: {
      type: DataTypes.MEDIUMINT
    },
    Topincode: {
      type: DataTypes.MEDIUMINT
    },
    Shipment_weight: {
      type: DataTypes.DECIMAL(19, 14)
    },
    chargable_weight: {
      type: DataTypes.DECIMAL(7, 2)
    },
    Shipment_value: {
      type: DataTypes.STRING(13)
    },
    Cft: {
      type: DataTypes.DECIMAL(3, 1)
    },
    Divisor: {
      type: DataTypes.DECIMAL(3, 1)
    },
    IsCod: {
      type: DataTypes.BOOLEAN
    },
    rate: {
      type: DataTypes.DECIMAL(6, 4)
    },
    totalAdditionalAmount: {
      type: DataTypes.DECIMAL(8, 2)
    },
    additionalCharges: {
      type: DataTypes.TEXT
    },
    Docketcharge: {
      type: DataTypes.DECIMAL(4, 1)
    },
    Fsc_percent: {
      type: DataTypes.DECIMAL(3, 1)
    },
    Fsc_amount: {
      type: DataTypes.DECIMAL(7, 2)
    },
    V_Fsc_amount: {
      type: DataTypes.DECIMAL(7, 2)
    },
    Greentax: {
      type: DataTypes.DECIMAL(4, 1)
    },
    Greentax_amount: {
      type: DataTypes.DECIMAL(6, 2)
    },
    min_Chargable_weight: {
      type: DataTypes.DECIMAL(4, 1)
    },
    minFreight: {
      type: DataTypes.DECIMAL(4, 1)
    },
    minFOV: {
      type: DataTypes.DECIMAL(4, 1)
    },
    fovPercentage: {
      type: DataTypes.DECIMAL(3, 2)
    },
    fov_amount: {
      type: DataTypes.DECIMAL(7, 2)
    },
    minODA: {
      type: DataTypes.DECIMAL(5, 1)
    },
    odaPerKG: {
      type: DataTypes.DECIMAL(3, 1)
    },
    oda_amount: {
      type: DataTypes.DECIMAL(7, 2)
    },
    handlingCharge: {
      type: DataTypes.DECIMAL(5, 1)
    },
    codAmount: {
      type: DataTypes.DECIMAL(4, 1)
    },
    taxableAmount: {
      type: DataTypes.DECIMAL(8, 2)
    },
    V_taxableAmount: {
      type: DataTypes.DECIMAL(8, 2)
    },
    gst: {
      type: DataTypes.DECIMAL(3, 1)
    },
    gst_Amount: {
      type: DataTypes.DECIMAL(8, 3)
    },
    V_gst_Amount: {
      type: DataTypes.DECIMAL(7, 2)
    },
    totalAmount: {
      type: DataTypes.DECIMAL(9, 3)
    },
    V_totalAmount: {
      type: DataTypes.DECIMAL(8, 2)
    },
    Isactive: {
      type: DataTypes.BOOLEAN
    },
    Deleted: {
      type: DataTypes.BOOLEAN
    },
    userId: {
      type: DataTypes.UUID // Use UUID data type,    
    },
    Customername: {
      type: DataTypes.STRING
    },
    neworder: {
      type: DataTypes.BOOLEAN
    },
    OrderStatus: {
      type: DataTypes.TINYINT
    },
    Itemname: {
      type: DataTypes.STRING
    },
    LSPDocketNo: {
      type: DataTypes.STRING
    },
    cancelremark: {
      type: DataTypes.STRING
    },
    rating: {
      type: DataTypes.DECIMAL(2, 1)
    },
    review: {
      type: DataTypes.STRING
    },
    servicetype: {
      type: DataTypes.STRING
    },
    ExpectedDelivery: {
      type: DataTypes.DATE
    },
    cancelled: {
      type: DataTypes.BOOLEAN
    },
    insurance: {
      type: DataTypes.TINYINT
    },
    iteminvoice: {
      type: DataTypes.STRING(42)
    },
    imgname: {
      type: DataTypes.STRING(99)
    },
    imagepath: {
      type: DataTypes.STRING(99)
    },
    deliveryaddressid: {
      type: DataTypes.STRING(4)
    },
    deliveryaddress: {
      type: DataTypes.TEXT
    },
    deliverypersonname: {
      type: DataTypes.STRING(63)
    },
    deliverypersonmobile: {
      type: DataTypes.BIGINT
    },
    deliveryslot: {
      type: DataTypes.STRING(55)
    },
    Pickupaddress: {
      type: DataTypes.TEXT
    },
    Pickuppersonmobile: {
      type: DataTypes.BIGINT
    },
    Pickuppersonname: {
      type: DataTypes.STRING(61)
    },
    pickuptime: {
      type: DataTypes.STRING(55)
    },
    returnaddress: {
      type: DataTypes.TEXT
    },
    returnpersonname: {
      type: DataTypes.STRING(61)
    },
    returnpersonmobile: {
      type: DataTypes.STRING(10)
    },
    returnremarks: {
      type: DataTypes.STRING(14)
    },

    MvikasDocketNo: {
      type: DataTypes.BIGINT
    },
    TransporterName: {
      type: DataTypes.STRING(21)
    },
    EWayBillNo: {
      type: DataTypes.STRING(15)
    },
    EWayBillExpDate: {
      type: DataTypes.STRING(19)
    },
    ItemCategory: {
      type: DataTypes.STRING(18)
    },
    ItemSubcategory: {
      type: DataTypes.STRING(7)
    },
    ItemType: {
      type: DataTypes.STRING(13)
    },
    PackagingRequired: {
      type: DataTypes.STRING(24)
    },
    QNTInvoiceNo: {
      type: DataTypes.STRING(16)
    },
    QNTOrderNo: {
      type: DataTypes.STRING(18)
    },
    PODUrl: {
      type: DataTypes.STRING(129)
    },
    DeliveryPersonEmail: {
      type: DataTypes.STRING(44)
    },
    OtherInfromation: {
      type: DataTypes.STRING(12)
    },
    PickupCompanyName: {
      type: DataTypes.STRING(64)
    },
    AssignedTo: {
      type: DataTypes.STRING(1)
    },
    ScanAt: {
      type: DataTypes.STRING
    },
    ScannerId: {
      type: DataTypes.STRING
    },
    VCodAmount: {
      type: DataTypes.DECIMAL(4, 1)
    },
    VFovAmount: {
      type: DataTypes.DECIMAL(6, 2)
    },
    VFovPercentage: {
      type: DataTypes.DECIMAL(2, 1)
    },
    VFscpercent: {
      type: DataTypes.STRING(4)
    },
    VGreenTax: {
      type: DataTypes.STRING(3)
    },
    VGreentaxAmount: {
      type: DataTypes.DECIMAL(6, 2)
    },
    VGst: {
      type: DataTypes.DECIMAL(7, 2)
    },
    VHandlingCharge: {
      type: DataTypes.DECIMAL(5, 1)
    },
    VMinChargableWeight: {
      type: DataTypes.DECIMAL(6, 2)
    },
    VMinFOV: {
      type: DataTypes.DECIMAL(4, 1)
    },
    VMinFreight: {
      type: DataTypes.DECIMAL(4, 1)
    },
    VMinODA: {
      type: DataTypes.DECIMAL(5, 1)
    },
    VOdaAmount: {
      type: DataTypes.DECIMAL(6, 2)
    },
    VOdaPerKG: {
      type: DataTypes.DECIMAL(3, 1)
    },
    VDocketCharge: {
      type: DataTypes.DECIMAL(4, 1)
    },
    VRate: {
      type: DataTypes.DECIMAL(3, 1)
    },
    PickupRequestNumber: {
      type: DataTypes.DECIMAL(10)
    },
    ShipmentDetails: {
      type: DataTypes.TEXT
    },
    ShipmentNumber: {
      type: DataTypes.STRING(12)
    },
    IsPickupCreate: {
      type: DataTypes.TINYINT
    },
    IsShipmentCreate: {
      type: DataTypes.TINYINT
    },
    IsPickupCancellation: {
      type: DataTypes.TINYINT
    },
    PickupAddressId: {
      type: DataTypes.STRING(4)
    },
    OrderPlacedFrom: {
      type: DataTypes.STRING(1)
    },
    PickupRequestDetails: {
      type: DataTypes.STRING(126)
    },
    TrackingAPIResponse: {
      type: DataTypes.TEXT
    },
    UpdateStatusResponse: {
      type: DataTypes.STRING(23)
    },
    LRNumber: {
      type: DataTypes.STRING
    },
    WareHouseName: {
      type: DataTypes.STRING(40)
    },
    Waybill: {
      type: DataTypes.STRING
    },
    CallBackResponse: {
      type: DataTypes.STRING
    },
    InvoiceJob_Id: {
      type: DataTypes.STRING
    },
    LabelPdfURL: {
      type: DataTypes.STRING
    },
    IsB2C: {
      type: DataTypes.TINYINT
    },
    IsBulkUpload: {
      type: DataTypes.TINYINT
    },
    IsUploadComplete: {
      type: DataTypes.TINYINT
    },
    AppointmentAt: {
      type: DataTypes.DATE,
      defaultValue: null
    },
    AppointmentCharge: {
      type: DataTypes.DECIMAL(10, 2)
    },
    FloorCharge: {
      type: DataTypes.DECIMAL(10, 2)
    },
    latestStatus: {
      type: DataTypes.INTEGER
    },
    VadditionalCharges: {
      type: DataTypes.TEXT
    },
    Vdeliveryslot: {
      type: DataTypes.STRING
    },
    Vpickuptime: {
      type: DataTypes.STRING
    },
    Vchargable_weight: {
      type: DataTypes.DECIMAL(10, 2)
    },
    specialCharge: {
      type: DataTypes.DECIMAL(10, 2)
    },
    VspecialCharge: {
      type: DataTypes.DECIMAL(10, 2)
    },
    rateType: {
      type: DataTypes.TINYINT,
      defaultValue: 1
    },
    kamId: {
      type: DataTypes.UUID
    },
    pickupmallCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    pickupsundayCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    pickupcsdCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    pickupfloorCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    pickupfloor: {
      type: DataTypes.STRING,
      defaultValue: null
    },
    pickupvmallCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    pickupvsundayCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    pickupvcsdCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    pickupappointmentCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    pickupappointmentAt: {
      type: DataTypes.DATE,
      defaultValue: null
    },
    pickupvappointmentCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    pickupvappointmentAt: {
      type: DataTypes.DATE,
      defaultValue: null
    },
    pickupvfloor: {
      type: DataTypes.STRING,
      defaultValue: null
    },
    pickupvfloorCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    pickupsundayDate: {
      type: DataTypes.DATE
    },
    vpickupsundayDate: {
      type: DataTypes.DATE
    },
    deliverymallCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    deliverysundayCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    deliverycsdCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    deliveryfloorCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    deliveryfloor: {
      type: DataTypes.STRING,
      defaultValue: null
    },
    deliveryvmallCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    deliveryvsundayCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    deliverysundayDate: {
      type: DataTypes.DATE
    },
    deliveryvsundayDate: {
      type: DataTypes.DATE
    },
    deliveryvcsdCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    deliveryappointmentCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    deliveryappointmentAt: {
      type: DataTypes.DATE,
      defaultValue: null
    },
    deliveryvappointmentCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    deliveryvappointmentAt: {
      type: DataTypes.DATE,
      defaultValue: null
    },
    deliveryvfloor: {
      type: DataTypes.STRING,
      defaultValue: null
    },
    deliveryvfloorCharge: {
      type: DataTypes.DECIMAL(10, 2),
      defaultValue: 0.0,
    },
    deletedAt: {
      type: DataTypes.DATE,
      defaultValue: null
    },
    createdAt: {
      allowNull: false,
      type: DataTypes.DATE
    },
    updatedAt: {
      allowNull: false,
      type: DataTypes.DATE
    }
  }, {
    sequelize,
    modelName: 'mvorder',
    paranoid: true
  });
  return mvorder;
};